using book_library.Models;

namespace book_library.Services;

public interface IBookService
{
    List<Book> GetAllBooks();
    List<Book> SearchBooks(string searchTerm);
}

public class BookService : IBookService
{
    private readonly List<Book> _books;

    public BookService()
    {
        _books = new List<Book>
        {
            new Book { Id = 1, Title = "To Kill a Mockingbird", Author = "Harper Lee", Genre = "Fiction", PublicationYear = 1960, ISBN = "978-0061120084", Description = "A classic novel about racism and injustice in the American South.", ImageUrl = "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1553383690i/2657.jpg" },
            new Book { Id = 2, Title = "1984", Author = "George Orwell", Genre = "Dystopian", PublicationYear = 1949, ISBN = "978-0451524935", Description = "A dystopian novel about totalitarianism and surveillance.", ImageUrl = "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1657781256i/61439040.jpg" },
            new Book { Id = 3, Title = "Pride and Prejudice", Author = "Jane Austen", Genre = "Romance", PublicationYear = 1813, ISBN = "978-0141439518", Description = "A romantic novel about manners and matrimony in Georgian England.", ImageUrl = "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1320399351i/1885.jpg" },
            new Book { Id = 4, Title = "The Great Gatsby", Author = "F. Scott Fitzgerald", Genre = "Fiction", PublicationYear = 1925, ISBN = "978-0743273565", Description = "A story of the Jazz Age and the American Dream.", ImageUrl = "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1490528560i/4671.jpg" },
            new Book { Id = 5, Title = "The Catcher in the Rye", Author = "J.D. Salinger", Genre = "Fiction", PublicationYear = 1951, ISBN = "978-0316769488", Description = "A coming-of-age story about teenage rebellion.", ImageUrl = "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1398034300i/5107.jpg" },
            new Book { Id = 6, Title = "Harry Potter and the Sorcerer's Stone", Author = "J.K. Rowling", Genre = "Fantasy", PublicationYear = 1997, ISBN = "978-0590353427", Description = "A young wizard discovers his magical heritage.", ImageUrl = "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1598823299i/42844155.jpg" },
            new Book { Id = 7, Title = "The Hobbit", Author = "J.R.R. Tolkien", Genre = "Fantasy", PublicationYear = 1937, ISBN = "978-0547928227", Description = "An adventure of a hobbit on a quest to reclaim treasure.", ImageUrl = "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1546071216i/5907.jpg" },
            new Book { Id = 8, Title = "The Lord of the Rings", Author = "J.R.R. Tolkien", Genre = "Fantasy", PublicationYear = 1954, ISBN = "978-0544003415", Description = "An epic quest to destroy an all-powerful ring.", ImageUrl = "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1566425108i/33.jpg" },
            new Book { Id = 9, Title = "Animal Farm", Author = "George Orwell", Genre = "Satire", PublicationYear = 1945, ISBN = "978-0452284241", Description = "A satirical allegory about revolution and power.", ImageUrl = "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1424037542i/170448.jpg" },
            new Book { Id = 10, Title = "Brave New World", Author = "Aldous Huxley", Genre = "Dystopian", PublicationYear = 1932, ISBN = "978-0060850524", Description = "A futuristic society where humans are engineered.", ImageUrl = "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1575509280i/5129.jpg" },
            new Book { Id = 11, Title = "The Chronicles of Narnia", Author = "C.S. Lewis", Genre = "Fantasy", PublicationYear = 1950, ISBN = "978-0066238500", Description = "Children discover a magical world through a wardrobe.", ImageUrl = "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1449868701i/11127.jpg" },
            new Book { Id = 12, Title = "Jane Eyre", Author = "Charlotte Brontë", Genre = "Romance", PublicationYear = 1847, ISBN = "978-0141441146", Description = "A governess falls in love with her mysterious employer.", ImageUrl = "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1557343311i/10210.jpg" },
            new Book { Id = 13, Title = "Wuthering Heights", Author = "Emily Brontë", Genre = "Gothic", PublicationYear = 1847, ISBN = "978-0141439556", Description = "A passionate and destructive love story on the moors.", ImageUrl = "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1587396303i/6185.jpg" },
            new Book { Id = 14, Title = "Moby-Dick", Author = "Herman Melville", Genre = "Adventure", PublicationYear = 1851, ISBN = "978-0142437247", Description = "Captain Ahab's obsessive quest for the white whale.", ImageUrl = "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1327940656i/153747.jpg" },
            new Book { Id = 15, Title = "The Odyssey", Author = "Homer", Genre = "Epic", PublicationYear = -800, ISBN = "978-0140268867", Description = "The epic journey of Odysseus returning home from war.", ImageUrl = "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1390173285i/1381.jpg" },
            new Book { Id = 16, Title = "Crime and Punishment", Author = "Fyodor Dostoevsky", Genre = "Philosophical", PublicationYear = 1866, ISBN = "978-0486415871", Description = "A psychological exploration of guilt and redemption.", ImageUrl = "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1382846449i/7144.jpg" },
            new Book { Id = 17, Title = "The Brothers Karamazov", Author = "Fyodor Dostoevsky", Genre = "Philosophical", PublicationYear = 1880, ISBN = "978-0374528379", Description = "A philosophical novel about faith, doubt, and morality.", ImageUrl = "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1427728126i/4934.jpg" },
            new Book { Id = 18, Title = "War and Peace", Author = "Leo Tolstoy", Genre = "Historical", PublicationYear = 1869, ISBN = "978-0199232765", Description = "An epic tale of Russian society during the Napoleonic era.", ImageUrl = "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1413215930i/656.jpg" },
            new Book { Id = 19, Title = "Anna Karenina", Author = "Leo Tolstoy", Genre = "Romance", PublicationYear = 1877, ISBN = "978-0143035008", Description = "A tragic love story in imperial Russia.", ImageUrl = "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1601352433i/15823480.jpg" },
            new Book { Id = 20, Title = "The Divine Comedy", Author = "Dante Alighieri", Genre = "Epic", PublicationYear = 1320, ISBN = "978-0142437223", Description = "A journey through Hell, Purgatory, and Paradise.", ImageUrl = "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1692644891i/6656.jpg" },
            new Book { Id = 21, Title = "Don Quixote", Author = "Miguel de Cervantes", Genre = "Satire", PublicationYear = 1605, ISBN = "978-0060934347", Description = "A knight errant's delusional adventures in Spain.", ImageUrl = "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1546112331i/3836.jpg" },
            new Book { Id = 22, Title = "Les Misérables", Author = "Victor Hugo", Genre = "Historical", PublicationYear = 1862, ISBN = "978-0451419439", Description = "A story of redemption and revolution in 19th century France.", ImageUrl = "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1411852091i/24280.jpg" },
            new Book { Id = 23, Title = "The Count of Monte Cristo", Author = "Alexandre Dumas", Genre = "Adventure", PublicationYear = 1844, ISBN = "978-0140449266", Description = "A tale of betrayal, imprisonment, and revenge.", ImageUrl = "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1611834134i/7126.jpg" },
            new Book { Id = 24, Title = "Frankenstein", Author = "Mary Shelley", Genre = "Gothic", PublicationYear = 1818, ISBN = "978-0486282114", Description = "A scientist creates a living creature with tragic consequences.", ImageUrl = "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1669159060i/35031085.jpg" },
            new Book { Id = 25, Title = "Dracula", Author = "Bram Stoker", Genre = "Horror", PublicationYear = 1897, ISBN = "978-0486411095", Description = "The classic vampire tale of Count Dracula.", ImageUrl = "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1387151694i/17245.jpg" },
            new Book { Id = 26, Title = "The Picture of Dorian Gray", Author = "Oscar Wilde", Genre = "Gothic", PublicationYear = 1890, ISBN = "978-0141439570", Description = "A man remains young while his portrait ages.", ImageUrl = "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1424596966i/5297.jpg" },
            new Book { Id = 27, Title = "Great Expectations", Author = "Charles Dickens", Genre = "Fiction", PublicationYear = 1861, ISBN = "978-0141439563", Description = "An orphan's journey from poverty to wealth.", ImageUrl = "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1327920219i/2623.jpg" },
            new Book { Id = 28, Title = "A Tale of Two Cities", Author = "Charles Dickens", Genre = "Historical", PublicationYear = 1859, ISBN = "978-0486406510", Description = "Set against the French Revolution, a story of sacrifice.", ImageUrl = "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1344922523i/1953.jpg" },
            new Book { Id = 29, Title = "The Adventures of Sherlock Holmes", Author = "Arthur Conan Doyle", Genre = "Mystery", PublicationYear = 1892, ISBN = "978-0486474915", Description = "Classic detective stories featuring Sherlock Holmes.", ImageUrl = "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1164045516i/3590.jpg" },
            new Book { Id = 30, Title = "The Little Prince", Author = "Antoine de Saint-Exupéry", Genre = "Children's", PublicationYear = 1943, ISBN = "978-0156012195", Description = "A philosophical tale about a young prince from another planet.", ImageUrl = "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1367545443i/157993.jpg" },
            new Book { Id = 31, Title = "The Alchemist", Author = "Paulo Coelho", Genre = "Fiction", PublicationYear = 1988, ISBN = "978-0062315007", Description = "A young shepherd's journey to find his personal legend and treasure.", ImageUrl = "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1483412266i/865.jpg" },
            new Book { Id = 32, Title = "The Bell Jar", Author = "Sylvia Plath", Genre = "Fiction", PublicationYear = 1963, ISBN = "978-0061148514", Description = "A semi-autobiographical novel about a young woman's mental breakdown.", ImageUrl = "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1554582218i/6514.jpg" },
            new Book { Id = 33, Title = "Slaughterhouse-Five", Author = "Kurt Vonnegut", Genre = "Science Fiction", PublicationYear = 1969, ISBN = "978-0385333849", Description = "A satirical novel about war and time travel.", ImageUrl = "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1440319389i/4981.jpg" },
            new Book { Id = 34, Title = "The Road", Author = "Cormac McCarthy", Genre = "Post-Apocalyptic", PublicationYear = 2006, ISBN = "978-0307387899", Description = "A father and son's journey through a post-apocalyptic America.", ImageUrl = "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1600241424i/6288.jpg" },
            new Book { Id = 35, Title = "Life of Pi", Author = "Yann Martel", Genre = "Adventure", PublicationYear = 2001, ISBN = "978-0156027328", Description = "A boy survives 227 days at sea with a Bengal tiger.", ImageUrl = "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1631251689i/4214.jpg" },
            new Book { Id = 36, Title = "The Kite Runner", Author = "Khaled Hosseini", Genre = "Fiction", PublicationYear = 2003, ISBN = "978-1594631931", Description = "A story of redemption set against Afghanistan's turbulent history.", ImageUrl = "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1579036753i/77203.jpg" },
            new Book { Id = 37, Title = "The Book Thief", Author = "Markus Zusak", Genre = "Historical", PublicationYear = 2005, ISBN = "978-0375842207", Description = "Death narrates a story of a girl who steals books in Nazi Germany.", ImageUrl = "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1522157426i/19063.jpg" },
            new Book { Id = 38, Title = "The Handmaid's Tale", Author = "Margaret Atwood", Genre = "Dystopian", PublicationYear = 1985, ISBN = "978-0385490818", Description = "A dystopian novel about a totalitarian theocratic society.", ImageUrl = "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1578028274i/38447.jpg" },
            new Book { Id = 39, Title = "Gone Girl", Author = "Gillian Flynn", Genre = "Mystery", PublicationYear = 2012, ISBN = "978-0307588371", Description = "A psychological thriller about a wife's disappearance.", ImageUrl = "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1554086139i/19288043.jpg" },
            new Book { Id = 40, Title = "The Hunger Games", Author = "Suzanne Collins", Genre = "Dystopian", PublicationYear = 2008, ISBN = "978-0439023481", Description = "A girl fights for survival in a televised death match.", ImageUrl = "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1586722975i/2767052.jpg" },
            new Book { Id = 41, Title = "To the Lighthouse", Author = "Virginia Woolf", Genre = "Modernist", PublicationYear = 1927, ISBN = "978-0156907392", Description = "A modernist novel exploring consciousness and time.", ImageUrl = "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1388194210i/59716.jpg" },
            new Book { Id = 42, Title = "One Hundred Years of Solitude", Author = "Gabriel García Márquez", Genre = "Magical Realism", PublicationYear = 1967, ISBN = "978-0060883287", Description = "The multi-generational story of the Buendía family in Macondo.", ImageUrl = "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1327881361i/320.jpg" },
            new Book { Id = 43, Title = "The Catcher in the Rye", Author = "J.D. Salinger", Genre = "Fiction", PublicationYear = 1951, ISBN = "978-0316769174", Description = "Holden Caulfield's weekend in New York City.", ImageUrl = "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1398034300i/5107.jpg" },
            new Book { Id = 44, Title = "The Grapes of Wrath", Author = "John Steinbeck", Genre = "Historical", PublicationYear = 1939, ISBN = "978-0143039433", Description = "A family's journey during the Great Depression.", ImageUrl = "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1511302904i/4395.jpg" },
            new Book { Id = 45, Title = "Beloved", Author = "Toni Morrison", Genre = "Fiction", PublicationYear = 1987, ISBN = "978-1400033416", Description = "A former slave haunted by the ghost of her daughter.", ImageUrl = "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1528238049i/6149.jpg" },
            new Book { Id = 46, Title = "Catch-22", Author = "Joseph Heller", Genre = "Satire", PublicationYear = 1961, ISBN = "978-1451626650", Description = "A satirical novel about the absurdity of war.", ImageUrl = "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1463157317i/168668.jpg" },
            new Book { Id = 47, Title = "The Color Purple", Author = "Alice Walker", Genre = "Fiction", PublicationYear = 1982, ISBN = "978-0156028356", Description = "Letters from Celie about her life in rural Georgia.", ImageUrl = "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1572294687i/11486.jpg" },
            new Book { Id = 48, Title = "Midnight's Children", Author = "Salman Rushdie", Genre = "Magical Realism", PublicationYear = 1981, ISBN = "978-0812976533", Description = "Children born at midnight on India's independence day.", ImageUrl = "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1385326977i/14836.jpg" },
            new Book { Id = 49, Title = "The Name of the Rose", Author = "Umberto Eco", Genre = "Mystery", PublicationYear = 1980, ISBN = "978-0156001311", Description = "A medieval murder mystery set in an Italian monastery.", ImageUrl = "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1415375471i/119073.jpg" },
            new Book { Id = 50, Title = "Their Eyes Were Watching God", Author = "Zora Neale Hurston", Genre = "Fiction", PublicationYear = 1937, ISBN = "978-0061120060", Description = "A woman's journey to self-discovery in the American South.", ImageUrl = "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1424438987i/37415.jpg" }
        };
    }

    public List<Book> GetAllBooks()
    {
        return _books;
    }

    public List<Book> SearchBooks(string searchTerm)
    {
        if (string.IsNullOrWhiteSpace(searchTerm))
        {
            return _books;
        }

        searchTerm = searchTerm.ToLower();
        return _books.Where(b => 
            b.Title.ToLower().Contains(searchTerm) || 
            b.Author.ToLower().Contains(searchTerm) ||
            b.Genre.ToLower().Contains(searchTerm) ||
            b.Description.ToLower().Contains(searchTerm)
        ).ToList();
    }
}
